### ISSUE TITLE
Investigate desire/feasibility of ditching exception handling

### ISSUE THREAD

**Issue by dashodanger** [MUD-Team/mud#16]
Try/catch, throw, etc, are prevalent in the code. Unknown at this time if these are actually necessary as a part of client/server architecture, etc.

**Comment by pbdot** [comment]
I've cleaned up exception handling, unifying from Error and FatalError to a single (fatal) Error exception type, which inherits from Poco::Exception.  Since adopting poco, we can't really compile without exceptions, so closing.
